version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cakeshop_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - cakeshop

  nginx:
    image: nginx:alpine
    container_name: cakeshop_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - cakeshop

  mysql:
    image: mysql:8.0
    container_name: cakeshop_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cakeshop_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: 223140172
      MYSQL_USER: cakeshop
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cakeshop

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cakeshop_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - cakeshop

networks:
  cakeshop:
    driver: bridge

volumes:
  mysql_data: